### ISSUE TITLE
CSS file not loaded

### ISSUE THREAD

**Issue by karensg** [JetBrains/hub-project-team-widget#2]
Hi guys,

I have issues with displaying the widget in my standalone installation.
![image](https://user-images.githubusercontent.com/359682/72995628-8540f800-3df9-11ea-86ad-6b8a1855a3bd.png)
It is trying to load `https://issues.mydomain.com/hub/api/rest/widgets/hub-project-team-widget/archive/main.2124.css` but gets a 400 error.

I am on the latest [docker release](https://hub.docker.com/layers/jetbrains/youtrack/2019.3.64090/images/sha256-2ea25d5b839f4aed2a3c8949c012e1d029a4791576e32980525da3ce38ead345) and as far as I can see, I am on version 1.2.3

Removing and readding does not work either.

**Comment by huston007** [comment]
@karensg Hello, thank you for reporting this. Could you please send us the content of that 400 server response?

**Comment by karensg** [comment]
The response seems empty:
![image](https://user-images.githubusercontent.com/359682/72997020-f681aa80-3dfb-11ea-8c55-9f3371e4652e.png)
When I curl this file:
```json
{ 
   "error":"widget-file-not-found",
   "error_code":400,
   "error_description":"The archive package does not contain the required main.2124.css file",
   "error_developer_message":"The archive package does not contain the required main.2124.css file",
   "error_uri":"https://www.jetbrains.com/help/hub/2019.1/HUB-REST-API.html",
   "error_params":[ 
      { 
         "name":"file",
         "value":"main.2124.css"
      }
   ]
}
```

**Comment by katriyna** [comment]
@karensg thank you for your complain.

Last widget update was mistakenly uploaded without *.css file. Now it is re-uploaded again correctly. Could you please visit page with list of installed custom widgets and update Project Team widget to latest version 1.2.4 (broken version 1.2.3 is now hidden from plugin repository)

**Comment by karensg** [comment]
Woow, it works now. Thanks for the super fast fix!
